import { NextRequest, NextResponse } from "next/server";

const BACKEND =
  process.env.NEXT_PUBLIC_API_URL ??
  "https://intuitive-blessing-production-30de.up.railway.app";

/**
 * Proxy the iCal feed from the backend.
 * This endpoint is public (no API key required) because it is meant to be
 * subscribed to directly from Google Calendar / Outlook — those clients
 * cannot send custom headers.  Authentication is via the HMAC token in the
 * query string which was generated by /api/v1/calendar/ics-token.
 */
export async function GET(req: NextRequest) {
  const token = req.nextUrl.searchParams.get("token") ?? "";
  const res = await fetch(
    `${BACKEND}/api/v1/calendar/ics-feed?token=${encodeURIComponent(token)}`,
    { headers: {} },
  );

  if (!res.ok) {
    return new NextResponse("Unauthorised or invalid token", { status: res.status });
  }

  const icsText = await res.text();
  return new NextResponse(icsText, {
    status: 200,
    headers: {
      "Content-Type": "text/calendar; charset=utf-8",
      "Content-Disposition": res.headers.get("content-disposition") ?? 'attachment; filename="nama.ics"',
      "Cache-Control": "no-cache, must-revalidate",
    },
  });
}
