"""
M8: Itinerary Model
---------------------
An Itinerary is a structured day-by-day travel plan generated by the
Itinerary Intelligence Agent (M8) from a qualified Lead.

State machine:
  DRAFT → SENT → ACCEPTED | REVISED | REJECTED

An accepted Itinerary becomes a Booking.

Key design decisions:
  - tenant_id FK enforces RLS (HS-2).
  - lead_id links the itinerary back to the CRM lead for traceability.
  - days_json stores the full AI-generated day-by-day plan as JSON
    (no separate ItineraryDay table — avoids over-normalisation for a
    document-style entity that is queried as a whole).
  - total_price is a denormalised sum kept in sync by the service layer.
  - version allows multiple revisions of the same itinerary.
"""

import enum
from sqlalchemy import (
    Column, Integer, String, Float, Text,
    ForeignKey, DateTime, Enum as SQLEnum, JSON, Index, Boolean
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.db.session import Base


class ItineraryStatus(str, enum.Enum):
    DRAFT    = "DRAFT"
    SENT     = "SENT"
    ACCEPTED = "ACCEPTED"
    REVISED  = "REVISED"
    REJECTED = "REJECTED"
    EXPIRED  = "EXPIRED"


class Itinerary(Base):
    """
    AI-generated itinerary for a qualified lead.
    """
    __tablename__ = "itineraries"

    id               = Column(Integer, primary_key=True, index=True)
    tenant_id        = Column(Integer, ForeignKey("tenants.id"), nullable=False, index=True)
    lead_id          = Column(Integer, ForeignKey("leads.id"),   nullable=False, index=True)
    created_by_user  = Column(Integer, ForeignKey("users.id"),   nullable=True)

    title            = Column(String(512), nullable=False)
    destination      = Column(String(512), nullable=False)
    duration_days    = Column(Integer,     nullable=False)
    traveler_count   = Column(Integer,     default=1)
    travel_style     = Column(String(64),  default="Standard")

    # Stored as list-of-ItineraryDay dicts (matches ItineraryDay Pydantic schema)
    days_json        = Column(JSON,  nullable=False, default=list)

    total_price      = Column(Float, nullable=False, default=0.0)
    currency         = Column(String(10), default="INR")
    margin_pct       = Column(Float, default=0.0)           # gross margin % for analytics

    status           = Column(SQLEnum(ItineraryStatus), nullable=False, default=ItineraryStatus.DRAFT)
    version          = Column(Integer, default=1)           # incremented on each revision
    agent_reasoning  = Column(Text, nullable=True)          # AI chain-of-thought for audit

    # Social media content (M9 — Content Intelligence)
    social_caption   = Column(Text,  nullable=True)
    social_hooks     = Column(JSON,  default=list)
    social_image_suggestions = Column(JSON, default=list)

    sent_at          = Column(DateTime(timezone=True), nullable=True)
    accepted_at      = Column(DateTime(timezone=True), nullable=True)
    rejected_at      = Column(DateTime(timezone=True), nullable=True)
    expires_at       = Column(DateTime(timezone=True), nullable=True)

    created_at       = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    updated_at       = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationships
    lead             = relationship("Lead",    foreign_keys=[lead_id])
    tenant           = relationship("Tenant",  foreign_keys=[tenant_id])
    bookings         = relationship("Booking", back_populates="itinerary", lazy="dynamic")

    __table_args__ = (
        Index("ix_itineraries_tenant_lead",   "tenant_id", "lead_id"),
        Index("ix_itineraries_tenant_status", "tenant_id", "status"),
    )
