[phases.setup]
nixPkgs = ["python310", "gcc", "postgresql"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "alembic upgrade head && gunicorn app.main:app --config gunicorn.conf.py"

[variables]
PYTHONPATH = "."
PYTHONUNBUFFERED = "1"
